# Generated by Django 3.1.7 on 2021-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_history', models.CharField(max_length=250)),
                ('dataBusca', models.DateTimeField(auto_now_add=True)),
                ('jsonDados', models.TextField()),
                ('cidade', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('temperature', models.CharField(max_length=100)),
            ],
        ),
    ]
